## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## allows failures on nightly julia
matrix:
  allow_failures:
   - julia: nightly

## test script
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("J4Org"); Pkg.test("J4Org"; coverage=true)'

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("J4Org")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

